### ISSUE TITLE
Kin vs similar environments

### ISSUE THREAD

**Issue by adonnini** [kinfoundation/kin-rfcs#4]
Hi, 

I read the Rewards Engine white paper a few times. I have the sense that we are still far away from a working system, even an alpha release. 

At this point, it's not clear to me why, as a developer, I would want to invest in applications for the Kin ecosystem as opposed to doing that for an ecosystem such as BitClave (www.bitclave.com) which appears to be already operational. 

The use cases used in the RW RFC are still not very compelling, and seem to be (too) closely related to Kik.

I think that until you publish a committed roadmap, it will be difficult for any developer to seriously consider developing apps for Kin.

By the way, the RE RFC is still pretty high-level. Although you should be congratulated for the open approach you are taking, you cannot expect the community (assuming there will be one) to do the heavy lifting as the RE RFC is not really a technical starting point for development, and this is not truly an open source project.

Sorry for being so critical. I have high expectations based on the the ideas described in the WP. I am disappointed that, based on what I see, the project has just started, and is a long way from becoming a reality.

I would appreciate some feedback about this. Thanks, Alex Donnini

**Comment by oryband** [comment]
Thanks for the criticism, but these multiple questions were already asked and answered multiple times on our discussion channels.

Furthermore this issue is not a comment or an update proposal for the RFC. Please keep generic product discussions where they should be: [/r/KinFoundation](https://www.reddit.com/r/KinFoundation/) or on our [Telegram groups](https://t.me/kinfoundation).

Closing this issue.
