### ISSUE TITLE
Marketplaces and direct exchanges

### ISSUE THREAD

**Issue by adonnini** [kinfoundation/kin-rfcs#6]
Hi,

If I am not mistaken, at a high level one of the key features of blockchain based platforms is that they participants to deal directly with each other without intermediaries.

More specifically, blockchain technology enables marketplaces where consumers and providers of products and services meet and exchange goods and services, and information for payments in cryptocurrency(ies) which can ultimately be exchanged for fiat currency.

Could you please explain to me if and how the Kin ecosystem will enable the creation of such marketplaces?

After reading the KRE white paper a number of times, I cannot see how marketplaces like the ones I described above are possible with Kin.

I may have misunderstood what Kin is all about. However, at this point, it appears to me that Kin is an environment where value creation is equivalent to app usage, i.e. you create value by using apps. I am puzzled. In a sense, I know I am exaggerating, Kin appears to be a new vehicle for having consumers pay app developers for their software (I do realize that users also are rewarded in Kin).

If my read of what Kin is all about is even partway correct, then my main feedback is that I do not see how Kin will be able to compete with other similar efforts unless it makes it possible for independent markeplaces to operate with the Kin ecosystem. I was counting on Kin to let me do that with my app.

Thanks.

**Comment by oryband** [comment]
Thanks for the criticism, but these multiple questions were already asked and answered more than once on our discussion channels.

Furthermore this issue is not a comment or an update proposal for any RFC. Please keep generic product discussions where they should be: [/r/KinFoundation](https://www.reddit.com/r/KinFoundation/) or on our [Telegram groups](https://t.me/kinfoundation).

Closing this issue.
